export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const ADD_ITEMS_REQUEST = "ADD_ITEMS_REQUEST";
export const ADD_ITEMS_SUCCESS = "ADD_ITEMS_SUCCESS";
export const ADD_ITEMS_FAILURE = "ADD_ITEMS_FAILURE";

export const DEL_ITEMS_REQUEST = "DEL_ITEMS_REQUEST";
export const DEL_ITEMS_SUCCESS = "DEL_ITEMS_SUCCESS";
export const DEL_ITEMS_FAILURE = "DEL_ITEMS_FAILURE";

export const PUT_ITEMS_REQUEST = "PUT_ITEMS_REQUEST";
export const PUT_ITEMS_SUCCESS = "PUT_ITEMS_SUCCESS";
export const PUT_ITEMS_FAILURE = "PUT_ITEMS_FAILURE";

export const PAGINATION_ITEMS_REQUEST = "PAGINATION_ITEMS_REQUEST";
export const PAGINATION_ITEMS_SUCCESS = "PAGINATION_ITEMS_SUCCESS";
export const PAGINATION_ITEMS_FAILURE = "PAGINATION_ITEMS_FAILURE";

export const SEARCH_ITEMS_REQUEST = "SEARCH_ITEMS_REQUEST";
export const SEARCH_ITEMS_SUCCESS = "SEARCH_ITEMS_SUCCESS";
export const SEARCH_ITEMS_FAILURE = "SEARCH_ITEMS_FAILURE";
